#MotorAdjPlus settings
#Fri Oct 02 01:00:16 CST 2026
bgMode=cover
sketchDir=
bgImage=C\:\\Users\\HurtMaker\\Desktop\\ps4 test\\HumanoidRobot_PS4\\Tools_MotorAdj\\background\\bg_1790872410145.jpg
mirror.count=12
ramUsed=791
mirror.0=1,8,R,1,S
mirror.2=3,10,R,1,S
mirror.1=2,9,R,1,S
flashUsed=22860
mirror.4=5,12,R,1,S
bgColor=
mirror.3=4,11,R,1,S
mirror.6=7,14,R,1,S
mirror.5=6,13,R,1,S
bgDim=79
motorSrc=
mirror.8=18,22,R,1,S
mirror.7=15,15,R,1,S
mirror.9=19,23,R,1,S
lastUploadTime=1790873774474
cli=
bgZoom=100
flashFrames=75
mirror.10=20,24,R,1,S
posBlock=100
mirror.11=21,25,R,1,S
bgX=50
ramMax=2560
port=
bgY=50
flashMax=28672
lastUpload=f0445b1f686166ff7a25ce73ed1dfed4
