#MotorAdjPlus settings
#Tue Oct 06 02:13:02 CST 2026
bgMode=cover
sketchDir=
bgImage=C\:\\Users\\HurtMaker\\Desktop\\ps4 test\\HumanoidRobot_PS4\\Tools_MotorAdj\\background\\bg_1791135025194.jpg
mirror.count=12
ramUsed=834
mirror.0=1,8,R,1,S
mirror.2=3,10,R,1,S
mirror.1=2,9,R,1,S
flashUsed=23396
mirror.4=5,12,R,1,S
bgColor=
mirror.3=4,11,R,1,S
mirror.6=7,14,R,1,S
mirror.5=6,13,R,1,S
bgDim=26
motorSrc=
mirror.8=18,22,R,1,S
mirror.7=15,15,R,1,S
theme=tech
mirror.9=19,23,R,1,S
lastUploadTime=1791223982764
monitorPort=COM1
cli=
blockLang=zh
bgZoom=100
flashFrames=60
mirror.10=20,24,R,1,S
posBlock=100
mirror.11=21,25,R,1,S
bgX=50
ramMax=2560
port=
bgY=50
flashMax=28672
lastUpload=fd1470489847c4f18cca03ee40f4b1d1
